### ISSUE TITLE
Not supported from package.module import class

### ISSUE THREAD

**Issue by zzl221000** [operatorequals/httpimport#54]
```
with httpimport.github_repo('operatorequals','covertutils'):
    from covertutils.handlers import BaseHandler
```

```
ImportError: cannot import name 'BaseHandler' from 'covertutils.handlers' (https://raw.githubusercontent.com/operatorequals/covertutils/master/covertutils/handlers/__init__.py)
```

httpimport version: 1.3.0

**Comment by operatorequals** [comment]
They way this module is made does not support direct attribute importing.

Try importing the whole sub-package and referencing the whole path in the code.

**Comment by zzl221000** [comment]
> They way this module is made does not support direct attribute importing.
> 
> Try importing the whole sub-package and referencing the whole path in the code.


import sub-package
```
with httpimport.github_repo('operatorequals','covertutils'):
    import covertutils.handlers
    print(covertutils.handlers.BaseHandler)
```
but
```
AttributeError: module 'covertutils.handlers' has no attribute 'BaseHandler'
```

@operatorequals

**Comment by operatorequals** [comment]
This is very weird as the unit tests pass. I'll have a look into it.

**Comment by rkbennett** [comment]
Looked at this a little bit, and I believe what is actually happening is that it's failing to import BaseHandler from basehandler because there are syntax errors in covertutils.handlers.basehandler which stops the import of covertutils.handlers.basehandler.BaseHandler, the same is true of covertutils.handlers.buffering
I have created an issue in that repo for this issue. The takeaway though is that before you attempt to import something remotely it's best practice to test a local import on a dev box to make sure the code can be imported properly. There is a bit of a gotcha with the imports where, if the import errors out it does so silently and doesn't clean out the sys.modules reference to the failed import.
Not sure if that can be fixed or not, depends on if you can catch the `exec()` error I believe. Might be worth creating a new issue on here to handle failed imports more gracefully as I think that's what the root issue is here.

**Comment by rkbennett** [comment]
Did some local testing and this appears to be tied to the import without sys_modules logic. The exception must be raised so that the import protocol can clean up the failed imports. I'm specifically looking here https://github.com/operatorequals/httpimport/blob/master/httpimport.py#L459
this can be fixed by simply assigning the BaseException to a variable and then raising it if sys_modules is true like this:
```
except BaseException as e:
  if not sys_modules:
    logger.warning(
      "[-] Module/Package '%s' cannot be imported without adding it to sys.modules. Might contain relative imports." % fullname)
  else:
    raise e
```

**Comment by operatorequals** [comment]
A new release has been created containing @rkbennett 's fix ([`v1.3.1`](https://github.com/operatorequals/httpimport/tree/v1.3.1)).

The `covertutils` package never made it to Python3, and in the old Python2 times, tabs and spaces were allowed to be mixed if I remember correctly!

Please provide some feedback if this did fix the Issue!

**Comment by zzl221000** [comment]
@operatorequals  Version 1.3.1 works fine with most libraries, only covertutils throws an error.

**Comment by operatorequals** [comment]
That's great!
I'm closing the issue now. Feel free to create a new one if a relevant problem occurs.


Thank you both for your input!

**Comment by rkbennett** [comment]
The fix I suggested on here was not in my commit and hasn't been updated in the code, may want to re-open this or update the code.
